/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Pledge = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'certificateId' : IDL.Text,
  'timestamp' : Time,
});
export const Certificate = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'getAdminPledges' : IDL.Func([IDL.Text], [IDL.Vec(Pledge)], ['query']),
  'getRecentCertificates' : IDL.Func([], [IDL.Vec(Certificate)], ['query']),
  'getTotalPledges' : IDL.Func([], [IDL.Nat], ['query']),
  'takePledge' : IDL.Func([IDL.Text, IDL.Text], [Certificate], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Pledge = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'certificateId' : IDL.Text,
    'timestamp' : Time,
  });
  const Certificate = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'getAdminPledges' : IDL.Func([IDL.Text], [IDL.Vec(Pledge)], ['query']),
    'getRecentCertificates' : IDL.Func([], [IDL.Vec(Certificate)], ['query']),
    'getTotalPledges' : IDL.Func([], [IDL.Nat], ['query']),
    'takePledge' : IDL.Func([IDL.Text, IDL.Text], [Certificate], []),
  });
};

export const init = ({ IDL }) => { return []; };